### ISSUE TITLE
Accept button to be removed once all hours have expired and replaced with system message

### ISSUE THREAD

**Issue by elenadanailova** [nworbnhoj/qwikgame#97]
Button "Accept" still appears as available even though there are no available hours to select (partially related to issue First available hour for invitation #95 )

Instead system message should appear stating the invitation has expired and accept button should be removed completely.

As recently discussed and as probably is now implemented, the appeal may be kept "until midnight of the Appeal Day (venue time)  This will give all Players with bids time to see the final log entries".  

![image](https://github.com/user-attachments/assets/8e090b8a-a393-4aff-a59e-94f8555dc12e)

**Comment by nworbnhoj** [comment]
resolved by: 3c7c87115b2d5b967938beaa527c14d4bfee0856

**Comment by elenadanailova** [comment]
This issue still persists. I suppose it might be related to the fact that I am looking at the invitation from Bulgaria where 20h on 2-FEB has still not passed?

https://alpha.qwikgame.org/appeal/59/

![Image](https://github.com/user-attachments/assets/147c5a22-0b40-41ea-8da3-91fb943e74e3)


https://alpha.qwikgame.org/appeal/57/

![Image](https://github.com/user-attachments/assets/6271ba35-933a-4626-9fdf-291bcb54d60b)

https://alpha.qwikgame.org/appeal/56/

![Image](https://github.com/user-attachments/assets/d3e5c325-a895-452c-bb9e-d2e1ae52d4e2)

**Comment by elenadanailova** [comment]
Invitation is still active for yesterday (1-FEB). 

Interestingly, the hours elapse in accordance to our BG time. The last offer of Rival 2 was made at 13.52 and 14 was still available. Now it is 15.50 in BG, next available hour is at 16. 

![Image](https://github.com/user-attachments/assets/827d90c7-adb2-4dc3-932b-637408278952)

**Comment by nworbnhoj** [comment]
The Offer button will now only show when the Appeal.status is **A**ctive.

The Offer button will NOT show then the Appeal.status is **C**ancelled, **D**ormant (a Match has been scheduled), or e**X**pired.
